const fs = require("fs/promises");
const path = require("path");
const crypto = require("crypto");

// sharp ships prebuilt native binaries for common platforms (including
// linux x64, which Hostinger's Node hosting runs on) - but on the off
// chance it fails to load in a given environment, fall back to storing the
// original upload unprocessed rather than crashing the whole upload flow.
let sharp = null;
try {
  sharp = require("sharp");
} catch (err) {
  console.warn("[upload] sharp unavailable, uploads will be stored without resizing/optimization:", err.message);
}

const MIME_TO_EXT = { "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp" };
const MAX_DIMENSION = 2400; // cap oversized uploads rather than serving 6000px hero photos as-is

const UPLOAD_ROOT = process.env.UPLOAD_DIR || path.join(__dirname, "..", "..", "uploads");

/**
 * processAndStoreImage
 * -----------------------
 * Takes a raw upload buffer, resizes it down if it's larger than needed,
 * re-encodes it for a smaller file size, and writes it to
 * /uploads/<category>/<generated-name>.<ext> using a randomly generated
 * filename (never the original, user-supplied one - avoids path traversal
 * and filename collisions entirely).
 *
 * Returns { storagePath, url, filename, width, height, sizeBytes }.
 */
async function processAndStoreImage({ buffer, mimetype, category = "general", publicUrlBase = "/uploads" }) {
  const ext = MIME_TO_EXT[mimetype];
  if (!ext) throw new Error("Unsupported image type.");

  const safeCategory = /^[a-z0-9_-]+$/i.test(category) ? category : "general";
  const filename = `${Date.now()}-${crypto.randomBytes(8).toString("hex")}.${ext}`;
  const dir = path.join(UPLOAD_ROOT, safeCategory);
  await fs.mkdir(dir, { recursive: true });
  const destPath = path.join(dir, filename);

  let finalBuffer = buffer;
  let width = null;
  let height = null;

  if (sharp) {
    let pipeline = sharp(buffer, { failOn: "none" }).rotate(); // auto-orient from EXIF
    const meta = await pipeline.metadata();
    if (meta.width && meta.width > MAX_DIMENSION) {
      pipeline = pipeline.resize({ width: MAX_DIMENSION, withoutEnlargement: true });
    }
    if (ext === "jpg") pipeline = pipeline.jpeg({ quality: 82, mozjpeg: true });
    else if (ext === "png") pipeline = pipeline.png({ quality: 82, compressionLevel: 8 });
    else if (ext === "webp") pipeline = pipeline.webp({ quality: 82 });

    finalBuffer = await pipeline.toBuffer();
    const finalMeta = await sharp(finalBuffer).metadata();
    width = finalMeta.width || null;
    height = finalMeta.height || null;
  }

  await fs.writeFile(destPath, finalBuffer);

  return {
    storagePath: path.join(safeCategory, filename),
    url: `${publicUrlBase}/${safeCategory}/${filename}`,
    filename,
    width,
    height,
    sizeBytes: finalBuffer.length,
  };
}

async function deleteStoredImage(storagePath) {
  const resolved = path.join(UPLOAD_ROOT, storagePath);
  // Guard against a storagePath ever escaping the uploads root (defence in
  // depth - storagePath is always generated by us, never user input, but
  // this makes that invariant explicit rather than assumed).
  if (!resolved.startsWith(UPLOAD_ROOT)) {
    throw new Error("Refusing to delete a path outside the uploads directory.");
  }
  await fs.unlink(resolved).catch(() => {}); // already gone is fine
}

module.exports = { processAndStoreImage, deleteStoredImage, UPLOAD_ROOT };
